export const SYNC_USERS = 'SYNC_USERS';
export const UPDATE_USER_COUNT = 'UPDATE_USER_COUNT';
export const UPDATE_USERS = 'UPDATE_USERS';
export const SET_USERDATA_TO_EDIT = 'SET_USERDATA_TO_EDIT';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const SET_USER_TO_DELETE = 'SET_USER_TO_DELETE';
export const DELETE_USER = 'DELETE_USER';